### ISSUE TITLE
length RNA

### ISSUE THREAD

**Issue by mtinti** [uci-cbcl/UFold#10]
Hi,
I'm getting an error when I try to predict RNA sequences longer than 600 bases:

Here is the error when I input sequences of 700 bases:

Welcome using UFold prediction tool!!!
Traceback (most recent call last):
  File "/cluster/majf_lab/mtinti/UFold/ufold_predict.py", line 328, in <module>
    main()
  File "/cluster/majf_lab/mtinti/UFold/ufold_predict.py", line 302, in main
    test_data = RNASSDataGenerator_input('data/', 'input')
  File "/cluster/majf_lab/mtinti/UFold/ufold/data_generator.py", line 217, in __init__
    self.load_data()
  File "/cluster/majf_lab/mtinti/UFold/ufold/data_generator.py", line 229, in load_data
    self.data_x = np.array([self.one_hot_600(item) for item in self.seq])
  File "/cluster/majf_lab/mtinti/UFold/ufold/data_generator.py", line 229, in <listcomp>
    self.data_x = np.array([self.one_hot_600(item) for item in self.seq])
  File "/cluster/majf_lab/mtinti/UFold/ufold/data_generator.py", line 244, in one_hot_600
    one_hot_matrix_600[:len(seq_item),] = feat
ValueError: could not broadcast input array from shape (700,4) into shape (600,4)

Is this expected? I thought I could go up to 1600bp...

Cheers
Michele

**Comment by mtinti** [comment]
Thanks for the speedy response!
I'll try your suggestions.

cheers
Michele
