### ISSUE TITLE
This error pops up when I tried to run Ufold

### ISSUE THREAD

**Issue by sfsdfd62** [uci-cbcl/UFold#16]
I downloaded the data from the website, and put them into the folder. But when I tried to run

 python ufold_test.py --test_files TS2

This pops up.

File "/miniconda3/envs/UFold/lib/python3.6/site-packages/munch/__init__.py", line 103, in __getattr__
    return object.__getattribute__(self, k)
AttributeError: 'Munch' object has no attribute 'test'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/miniconda3/envs/UFold/lib/python3.6/site-packages/munch/__init__.py", line 106, in __getattr__
    return self[k]
KeyError: 'test'

Could you tell me what might be the problem? Thank you !

**Comment by sperfu** [comment]
Hi there,

I'm afraid the problem occurs probably because of the package version issue. Could you please check the version of Munch package to see whether it match the software requirement?

Thanks
